app/blueprints/page/views.py
from flask import Blueprint, render_template, flash
from app.extensions import cache, timeout
from config import settings
from app.extensions import db, csrf
from flask import redirect, url_for, request, current_app
from flask_login import current_user, login_required
import requests
import ast
import json
import traceback
from sqlalchemy import and_, exists, text
from importlib import import_module
import os
import random

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    test = not current_app.config.get('PRODUCTION')
    if current_user.is_authenticated:
        return redirect(url_for('user.dashboard'))

    from app.blueprints.api.domain.domain import get_dropping_domains, get_drop_count
    from app.blueprints.api.api_functions import active_tlds

    dropping, drop_count = get_dropping_domains(40)
    random.shuffle(dropping)

    return render_template('page/index.html',
                           plans=settings.STRIPE_PLANS,
                           dropping=dropping,
                           test=test,
                           drop_count=drop_count,
                           tlds=active_tlds())


@page.route('/<domain>/', methods=['GET'])
@csrf.exempt
def parked(domain):
    if domain is not None:
        from app.blueprints.api.models.domains import Domain
        if db.session.query(exists().where(and_(Domain.name == domain, Domain.registered.is_(True)))).scalar():
            return render_template('page/domain.html', domain=domain)

    return redirect(url_for('page.home'))


@page.route('/availability', methods=['GET','POST'])
@csrf.exempt
def availability():
    if request.method == 'POST':

        # from app.blueprints.api.api_functions import save_search
        from app.blueprints.api.domain.domain import get_domain_availability, get_domain_details, get_dropping_domains, get_domain

        domain_name = get_domain(request.form['domain'])
        if domain_name is None:
            flash("This domain is invalid. Please try again.", "error")
            return redirect(url_for('page.home'))

        domain = get_domain_availability(domain_name)

        # 500 is the error returned if the domain is valid but can't be backordered
        if domain == 500:
            flash("This domain extension can't be backordered. Please try another domain extension.", "error")
            return redirect(url_for('page.home'))

        if domain is not None and 'available' in domain and domain['available'] is not None:
            # Save the search if it is a valid domain
            # if domain['available'] is not None:
            #     save_search(domain_name, domain['expires'], domain['date_available'], 3)  # '3' is the admin ID

            details = get_domain_details(domain_name)
            dropping = get_dropping_domains()

            return render_template('page/index.html', domain=domain, details=details, dropping=dropping)

        flash("This domain is invalid. Please try again.", "error")
        return redirect(url_for('page.home'))

    return render_template('page/index.html', plans=settings.STRIPE_PLANS)


@page.route('/view/<domain>/<available>', methods=['GET','POST'])
@csrf.exempt
def view(domain, available):

    if current_user.is_authenticated:
        id = current_user.id
    else:
        id = 0

    available = available.replace('-', '/')
    from app.blueprints.api.api_functions import save_search
    save_search(domain, available, available, id)
    return render_template('page/view.html', domain=domain, available=available)


# @page.route('/drops/<tld>', methods=['GET','POST'])
@page.route('/drops', methods=['GET','POST'])
@csrf.exempt
def drops():
    from app.blueprints.api.api_functions import active_tlds
    from app.blueprints.api.domain.domain import get_dropping_domains
    from app.blueprints.api.domain.s3 import get_last_modified

    domains, drop_count = get_dropping_domains()
    last_updated = get_last_modified()

    return render_template('user/drops.html',
                           listing=None,
                           domains=domains,
                           tlds=active_tlds(),
                           drop_count=drop_count,
                           current_user=current_user,
                           last_updated=last_updated)


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')


@page.route('/index')
def index():
    return render_template('page/index.html', plans=settings.STRIPE_PLANS)


# Callbacks.
@page.route('/callback/<app>', methods=['GET', 'POST'])
@csrf.exempt
def callback(app):
    module = import_module("app.blueprints.api.apps." + app + "." + app)
    app_callback = getattr(module, 'callback')
    return app_callback(request)


# Webhooks -------------------------------------------------------------------
@page.route('/webhook/<app>', methods=['GET','POST'])
@csrf.exempt
def webhook(app):
    try:
        module = import_module("app.blueprints.api.apps." + app + ".webhook")
        call_webhook = getattr(module, 'webhook')

        return call_webhook(request)
    except Exception:
        return json.dumps({'success': False}), 500, {'ContentType': 'application/json'}


# Pagination for /drops route
class PageResult:
    def __init__(self, data, tld, page = 1, number = 20):
        self.__dict__ = dict(zip(['data', 'tld', 'page', 'number'], [data, tld, page, number]))
        self.full_listing = [self.data[i:i+number] for i in range(0, len(self.data), number)]
    def __iter__(self):
        for i in self.full_listing[self.page-1]:
            yield i
    def __repr__(self): #used for page linking
        # return "/drops/{0}/{1}".format(self.tld, str(self.page+1)) #view the next page
        return '/drops/' + str(self.tld) + '/' + str(int(self.page)+1)

app/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    Markup,
    url_for,
    render_template,
    current_app,
    json,
    jsonify,
    session)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

import time
import random

from lib.safe_next_url import safe_next_url
from app.blueprints.user.decorators import anonymous_required
from app.blueprints.user.models import User
from app.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)

import re
import os
import pytz
import stripe
import datetime
from datetime import datetime as dt
from app.extensions import cache, csrf, timeout, db
from importlib import import_module
from sqlalchemy import or_, and_, exists
from app.blueprints.billing.charge import (
    stripe_checkout,
    create_payment,
    delete_payment,
    charge_card,
    get_payment_method,
    get_card
)
from app.blueprints.api.models.domains import Domain
from app.blueprints.billing.models.customer import Customer
from app.blueprints.api.models.searched import SearchedDomain
from app.blueprints.api.models.backorder import Backorder
from app.blueprints.api.api_functions import (
    save_domain,
    # save_search,
    valid_tlds,
    active_tlds,
    update_customer,
    print_traceback,
    create_backorder
)
from app.blueprints.api.domain.domain import (
    get_domain_details,
    get_domain_availability,
    get_domain,
    get_domain_expiration as get_expiry
)
from app.blueprints.api.domain.dynadot import (
    register_domain as register,
    delete_backorder_request,
    get_domain_expiration,
    backorder_request,
    set_whois_info,
    is_pending_delete
)

user = Blueprint('user', __name__, template_folder='templates')

# Login and Credentials -------------------------------------------------------------------
@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
# @cache.cached(timeout=timeout)
@csrf.exempt
def login():

    # This redirects to the link that the button was sending to before login
    form = LoginForm(next=request.args.get('next'))

    # This redirects to dashboard always.
    # form = LoginForm(next=url_for('user.dashboard'))

    if form.validate_on_submit():

        u = User.find_by_identity(request.form.get('identity'))

        if u and u.is_active() and u.authenticated(password=request.form.get('password')):
            # As you can see remember me is always enabled, this was a design
            # decision I made because more often than not users want this
            # enabled. This allows for a less complicated login form.
            #
            # If however you want them to be able to select whether or not they
            # should remain logged in then perform the following 3 steps:
            # 1) Replace 'True' below with: request.form.get('remember', False)
            # 2) Uncomment the 'remember' field in user/forms.py#LoginForm
            # 3) Add a checkbox to the login form with the id/name 'remember'
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                next_url = request.form.get('next')

                if next_url == url_for('user.login') or next_url == '' or next_url is None:
                    next_url = url_for('user.dashboard')

                if next_url:
                    return redirect(safe_next_url(next_url), code=307)

                if current_user.role == 'admin':
                    return redirect(url_for('admin.dashboard'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Your username/email or password is incorrect.', 'error')

    else:
        if len(form.errors) > 0:
            print(form.errors)

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
# @cache.cached(timeout=timeout)
def logout():
    logout_user()

    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.dashboard'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
@csrf.exempt
# @cache.cached(timeout=timeout)
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        if db.session.query(exists().where(User.email == request.form.get('email'))).scalar():
            flash('There is already an account with this email. Please login.', 'error')
            return redirect(url_for('user.login'))

        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):

            from app.blueprints.user.tasks import send_welcome_email
            from app.blueprints.contact.mailerlite import create_subscriber

            send_welcome_email.delay(current_user.email)
            create_subscriber(current_user.email)

            flash("You've successfully signed up!", 'success')
            return redirect(url_for('user.dashboard'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.dashboard'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Your username has been set.', 'success')
        return redirect(url_for('user.dashboard'))

    return render_template('user/welcome.html', form=form, payment=current_user.payment_id)


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.dashboard'))

    return render_template('user/update_credentials.html', form=form)


# Dashboard -------------------------------------------------------------------
@user.route('/dashboard', methods=['GET','POST'])
@login_required
@csrf.exempt
def dashboard():
    if current_user.role == 'admin':
        return redirect(url_for('admin.dashboard'))

    test = not current_app.config.get('PRODUCTION')

    domains = Backorder.query.filter(Backorder.user_id == current_user.id).all()
    searched = SearchedDomain.query.filter(SearchedDomain.user_id == current_user.id).order_by(SearchedDomain.id.desc()).limit(20).all()
    tlds = active_tlds()

    from app.blueprints.api.domain.domain import get_dropping_domains, get_drop_count
    dropping, drop_count = get_dropping_domains(40)

    # Shuffle the domains to spice things up a little
    random.shuffle(dropping)

    # Sort the searches by date
    searched.sort(key=lambda x: x.created_on, reverse=True)

    return render_template('user/dashboard.html', current_user=current_user,
                           domains=domains,
                           test=test,
                           searched=searched,
                           tlds=tlds,
                           dropping=dropping,
                           drop_count=drop_count)


# Domain Functions -------------------------------------------------------------------
@user.route('/check_availability', methods=['GET', 'POST'])
@login_required
@csrf.exempt
def check_availability():
    try:
        domain_name = ''
        if request.method == 'GET':
            if 'domain' not in request.args or 'available' not in request.args:
                return redirect(url_for('user.dashboard'))

            domain_name = get_domain(request.args.get('domain'))

        if request.method == 'POST':
            if 'domain' not in request.args and 'domain' not in request.form:
                flash("Something went wrong! Please try again.", "error")
                return redirect(url_for('user.dashboard'))

            if 'domain' in request.form:
                domain_name = get_domain(request.form['domain'])
            else:
                domain_name = get_domain(request.args.get('domain'))

            # Uncomment this when ready to check multiple domains at once
            # domains = [l for l in request.form['domains'].split('\n') if l]

        if domain_name is None:

app/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container" style="font-family: 'Gotham', sans-serif;margin-top:7px;margin-bottom:7px;min-width:95%;">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          {% if current_user.is_authenticated %}
              {% if current_user.role == 'member' %}
                <a href="{{ url_for('page.home') }}">
                  <span style="font-family:'Fredoka One', sans-serif !important; font-weight:200;font-size:36px;color:#0073ff;margin-left:10px;">{{ 'site_name'|site_name_filter }}</span>
                </a>
              {% else %}
                  <a href="{{ url_for('admin.dashboard') }}">
                    <span style="font-family:'Fredoka One', sans-serif !important; font-weight:200;font-size:36px;color:#0073ff;margin-left:10px;">{{ 'site_name'|site_name_filter }}</span>
                    </a>
              {% endif %}
          {% else %}
          <a href="{{ url_for('page.home') }}">
          <span style="font-family:'Fredoka One', sans-serif !important; font-weight:200;font-size:36px;color:#0073ff;margin-left:10px;">{{ 'site_name'|site_name_filter }}</span>
        </a>
          {% endif %}
      </div>
      <div id="navbar" class="collapse navbar-collapse font-weight__700 mx-lg-4">
        <ul class="nav navbar-nav navbar-right" style="display:inline">
          {% if current_user.role == 'admin' %}
            <li>
              {% include 'admin/_menu.html' %}
            </li>
          {% endif %}
          {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
          {% else %}
            <li><a style="padding:10px;" href="{{ url_for('billing.pricing') }}"><span style="font-family: 'Montserrat', sans-serif !important;font-weight:300;letter-spacing: 1.5px;color:#555555;">Pricing</span></a></li>
            <li><a style="padding:10px;" href="{{ url_for('user.contact') }}"><span style="font-family: 'Montserrat', sans-serif !important;font-weight:300;letter-spacing: 1.5px;color:#555555;">Contact Us</span></a></li>
            <li><a style="padding:10px;" href="{{ url_for('user.login') }}"><span style="font-family: 'Montserrat', sans-serif !important;font-weight:300;letter-spacing: 1.5px;color:#555555;">Login</span></a></li>
            <li style=background-color:#4dabf7;border-radius:4px;"><a style="padding:10px;" href="{{ url_for('user.signup') }}"><span style="font-size:12px; font-family: 'Montserrat', sans-serif !important;letter-spacing: 2.5px;color:#fff;">Sign up</span></a></li>

          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block footer %}
  <!--li><a href="{{ url_for('user.contact') }}">Contact</a></li>
  <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
  <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li-->
{% endblock %}

app/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}
{% import 'billing/macros/billing.html' as billing with context %}

<!DOCTYPE html>
<html style="max-width:100%;">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117689313-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-117689313-1');
    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="../../static/favicon.ico">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <!--link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}"-->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">

    <!-- Theme CSS -->
    <!-- Animation library for notifications   -->

    <!--  Light Bootstrap Table core CSS    --
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/theme/light-bootstrap-dashboard.css?v=1.4.0') }}"-->

    <!-- Bootstrap Theme -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/theme/bootstrap.min.css') }}">

      <!-- Javascript loader -->

    <!-- Theme Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Cabin|Gotham|Gotham|Roboto|Comfortaa"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">

    <!-- Lite elements -->

    <!-- Bootstrap Core CSS -->
    <!--<link
      rel="stylesheet"
      href="{{ url_for('static', filename='page/assets/plugins/bootstrap/css/bootstrap.min.css') }}">-->
    <!--<link rel="stylesheet" type="text/css" href="../../blueprints/page/templates/assets/plugins/bootstrap/css/bootstrap.min.css">-->

    <!-- Custom CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='page/lite/css/style.css') }}">
    <!--<link rel="stylesheet" type="text/css" href="../../blueprints/page/templates/lite/css/style.css">-->

    <!-- chartist CSS --
    <link href="../../blueprints/page/templates/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
    <link href="../../blueprints/page/templates/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
    <link href="../../blueprints/page/templates/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <!--This page css - Morris CSS --
    <link href="../../blueprints/page/templates/assets/plugins/c3-master/c3.min.css" rel="stylesheet">

    <!-- You can change the theme colors from here -->
    <!--link href="../../blueprints/page/templates/lite/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <!-- end Lite elements -->




    <script
      src="https://code.jquery.com/jquery-1.12.2.min.js"
      integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
      crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v2/"></script>

    {% if config['ANALYTICS_GOOGLE_UA'] %}
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.gmail-analytics.com/analytics.js','ga');

        ga('create', "{{ config['ANALYTICS_GOOGLE_UA'] }}", 'auto');
        ga('send', 'pageview');
      </script>
    {% endif %}

  </head>
  {% block litebody %}{% endblock %}
  <body class="font-w300;" style="margin:auto;width:100%;max-width:100%;overflow-x:hidden;padding-bottom:0; background-color:#fff;">
    {% block header %}{% endblock %}

    {% if request.path != '/demo' and request.path != '/inbox' and request.path != '/refresh'
    and request.path != '/rules' and not ('/add' in request.path) and not ('/parse' in request.path)
    and not ('/export' in request.path) and not ('/view_email' in request.path) %}
    <main class="container"style="min-height:850px;">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>
    {% endif %}
    <br /><br />
    {% block footer %}{% endblock %}
    <!--footer class="footer text-center" style="font-family: 'Gotham', sans-serif;">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Domain &copy; {{ current_year() }}</li>

        </ul>
      </div>
    </footer-->

<!-- Footer -->
        <footer class="footer section bg-light-primary text-gray pt-2">
            <div class="container" style="min-width:80%; max-width:95%;">
                <!-- Empty Space --
                <div class="lg-space"></div>
                <!--/ End Empty Space --
                <div class="row">
                    <div class="col-10 col-lg-8 mx-auto">
                        <div class="row">
                            <ul class="nav col flex-column sm-font-size">
                                <li class="nav-link nav-head text-uppercase font-weight__500 text-black base-font-size font-family-secondary">Company</li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Features</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Pricing</a></li>
                            </ul>
                            <ul class="nav col flex-column sm-font-size">
                                <li class="nav-link nav-head text-uppercase font-weight__500 text-black base-font-size font-family-secondary">Support</li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Help</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">FAQ</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Contact</a></li>
                            </ul>
                            <ul class="nav col flex-column sm-font-size">
                                <li class="nav-link nav-head text-uppercase font-weight__500 text-black base-font-size font-family-secondary">Legal</li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Terms</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Privacy</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Policy</a></li>
                            </ul>
                            <ul class="nav col flex-column sm-font-size">
                                <li class="nav-link nav-head text-uppercase font-weight__500 text-black base-font-size font-family-secondary">Press</li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Press Release</a></li>
                                <li class="nav-item"><a href="#" class="nav-link text-gray">Press Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Empty Space --
                <div class="lg-space"></div>
                <!--/ End Empty Space -->
                <div class="row align-items-center">
                    <div class="col-8 col-lg-8 pr-lg-0" style="padding:0;float:right">
                        <div class="credit sm-font-size text-right text-lg-right text-dark-gray">
                            <a href="{{ url_for('user.contact') }}">Contact Us</a> | <a href="{{ url_for('page.privacy') }}">Privacy Policy</a> | <a href="{{ url_for('page.terms') }}">Terms of Service</a>

                        </div>
                        <div class="copyright xs-font-size text-right text-lg-right">
                            &copy; 2020 {{ 'site_name'|site_name_filter }}. All Rights Reserved.
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--/ End Footer -->

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/main.js') }}">
    </script>
  </body>
</html>